services:
  web:
    container_name: prayer_player
    tty: true
    stdin_open: true
    restart: always
    expose: 
      - 8000
    network_mode: host
    build:
      context: .
      dockerfile: docker/DOCKERFILE
    image: prayer-player
    volumes:
      - /etc/localtime:/etc/localtime
      - ./backend:/app
    environment:
      - FLASK_ENV=development 
