version: '3'
services:
  web:
    container_name: prayer_player
    tty: true
    stdin_open: true
    expose: 
      - 8000
    ports:
      - "8000:8000"
    network_mode: host
    build:
      context: .
      dockerfile: docker/DOCKERFILE
    image: prayer-player
    volumes:
      - /etc/localtime:/etc/localtime
      - ./backend/logs:/app/logs/
    environment:
      - FLASK_ENV=development 
