device:
  volume: 25
calculationMethods:
  - description: "Muslim World League"
    id: 1
  - description: "Islamic Society of North America"
    id: 2
  - description: "Umm Al-Qura University, Makkah"
    id: 3
  - description: "Egyptian General Authority of Survey"
    id: 4
  - description: "University of Islamic Sciences, Karachi"
    id: 5
  - description: "Institute of Geophysics, University of Tehran"
    id: 6
  - description: "Shia Ithna-Ashari, Leva Institute, Qum"
    id: 7
  - description: "Gulf Region"
    id: 8
  - description: "Kuwait"
    id: 9
  - description: "Qatar"
    id: 10
  - description: "Majlis Ugama Islam Singapura, Singapore"
    id: 11
  - description: "Union Organization islamic de France"
    id: 12
  - description: "Diyanet İşleri Başkanlığı, Turkey"
    id: 13
  - description: "Spiritual Administration of Muslims of Russia"
    id: 14
  - description: "Moonsighting Committee"
    id: 15
  - description: "Dubai, UAE"
    id: 16 # - this is not an official calculation but based on the research done by the Batoul Apps team which uses 18.2 degrees for both Fajr and Isha
api:
  byCalendarByAdressURL: "http://api.aladhan.com/v1/calendarByAddress"
  accurateAdress: "Nantes, France"
  selectedMethod: 11
playlist:
  port: 8000
  dirToServe: "server/audio"
  url : "/azan1.mp3"
  # url : "http://88.126.184.174:14656/share/OptHmgaBchsY6Iqq/azan1.mp3"

